before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - "-s -w -extldflags '-static'"
    targets:
      - linux_386
      - linux_amd64
      - linux_arm
      - windows_amd64
      - darwin_amd64
dist: bin
archives:
  - format: binary
checksum:
  name_template: "checksums.txt"
release:
  name_template: "{{ .ProjectName }}"
changelog:
  skip: true
# snapshot:
#   name_template: "{{ .Tag }}-next"
# changelog:
#   sort: asc
#   filters:
#     exclude:
#       - "^docs:"
#       - "^test:"
