name: Tag
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.2

      - name: Run Golang CI Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.33

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}

      - name: FPM Upload Tag
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_TOKEN: ${{ secrets.BINTRAY_TOKEN }}
        run: |
          curl -u${BINTRAY_USER}:${BINTRAY_TOKEN} --data '{"name":"${{ steps.get_version.outputs.VERSION }}","desc":"${{ steps.get_version.outputs.VERSION }}"}' https://api.bintray.com//packages/dummyreleaserio/dummyreleaser-deb/dummyreleaser/versions
          curl -T dummyreleaser_${{ steps.get_version.outputs.VERSION }}_amd64.deb -u${BINTRAY_USER}:${BINTRAY_TOKEN} "https://api.bintray.com/content/dummyreleaserio/dummyreleaser-deb/dummyreleaser/${{ steps.get_version.outputs.VERSION }}/pool/dummyreleaser_${{ steps.get_version.outputs.VERSION }}_amd64.deb;deb_distribution=stable;deb_component=main;deb_architecture=amd64"
          curl -u${BINTRAY_USER}:${BINTRAY_TOKEN} --data '{"discard":true,"publish_wait_for_secs":,"subject":"dummyreleaser.io"}' "https://api.bintray.com/content/dummyreleaserio/dummyreleaser-deb/dummyreleaser/${{ steps.get_version.outputs.VERSION }}/publish"
          curl -u${BINTRAY_USER}:${BINTRAY_TOKEN} --data '{"name":"${{ steps.get_version.outputs.VERSION }}","desc":"${{ steps.get_version.outputs.VERSION }}"}' https://api.bintray.com//packages/dummyreleaserio/dummyreleaser-rpm/dummyreleaser/versions
          curl -T dummyreleaser-${{ steps.get_version.outputs.VERSION }}.x86_64.rpm -u${BINTRAY_USER}:${BINTRAY_TOKEN} "https://api.bintray.com/content/dummyreleaserio/dummyreleaser-rpm/dummyreleaser/${{ steps.get_version.outputs.VERSION }}/pool/dummyreleaser-${{ steps.get_version.outputs.VERSION }}.x86_64.rpm"
          curl -u${BINTRAY_USER}:${BINTRAY_TOKEN} --data '{"discard":true,"publish_wait_for_secs":,"subject":"dummyreleaser.io"}' "https://api.bintray.com/content/dummyreleaserio/dummyreleaser-rpm/dummyreleaser/${{ steps.get_version.outputs.VERSION }}/publish"
